# main text of home
name: Scott Santarromana
bio: Salesforce Architect @ RevenueWell

# twitter summary info
description: scott's blog

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile2.jpg


url: http://scosant.github.io

permalink: /:title/

# list of collections
collections:
  project-01:
    output: true
    title: project-01
    description: placeholder

# To enable google analytics, supply your token below
# analytics-google: 'UA-MYANALYTICS'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: scosant # enter this from your disqus account
  categories: [blog, project] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: scosant
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: scosant
# 500px: scosant
# youtube: myyoutube
# spotify: myspotify
github: scosant
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
# reddit: username
# medium: scosant
# vimeo: myvimeo
# email: scott.santarromana@gmail.com

authors:
    scott:
        name: scott
        bio: salesforc architect @ revenuewell
        external-image: false
        picture: assets/images/profile.jpg
        twitter: scosant

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
#paginate: 5
#paginate_path: "blog/:num/"

# enabled pages
showBlog: true
showCollections: true
showAbout: true

read-time: true   # do you want to show the "read time" of the posts?
show-tags: true   # do you want to show the "tags" inside the posts?
related: true     # related posts inside a post?

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

gems:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  #- jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

assets:
  cache: true
